name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show Swift version
        run: swift --version

      - name: Build debug target
        run: swift build

      - name: Build release target
        run: swift build -c release
